version: "3"

networks:
  auth-server:

volumes:
  auth-server-db-data:
  auth-server-redis-data:

services:
  auth-server-db:
    image: bitnami/mysql:8.0
    container_name: auth-server-db
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=development
      - MYSQL_USER=auth-server
      - MYSQL_PASSWORD=development
      - MYSQL_DATABASE=auth-server
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - auth-server-db-data:/bitnami/mysql/data
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - auth-server
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 2s
      timeout: 20s
      retries: 10

  auth-server-redis:
    image: bitnami/redis:latest
    container_name: auth-server-redis
    volumes:
      - auth-server-redis-data:/bitnami/redis/data
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=development
    ports:
      - "6379:6379"
    networks:
      - auth-server
